routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/employee', function () {
    return view('employee-page');
});

Route::get('/employee-calendar', function () {
    return view('employee-calendar');
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $casts = [
        'birthDate' => 'date',
    ];

    public function getPhotoLinkAttribute(): string
    {
        return asset('storage/'.$this->photo);
    }
}

app/Http/Livewire/AddEmployee.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use App\Models\Employee;
use Illuminate\View\View;
use Livewire\Component;
use Livewire\TemporaryUploadedFile;
use Livewire\WithFileUploads;

class AddEmployee extends Component
{
    use WithFileUploads;

    public const EMPLOYEE_PROPERTIES = [
        [
            'caption' => 'Username',
            'name' => 'username',
            'type' => 'text',
            'validation' => 'required|min:6|unique:employees,username',
        ],
        [
            'caption' => 'Name',
            'name' => 'name',
            'type' => 'text',
            'validation' => 'required',
        ],
        [
            'caption' => 'Surname',
            'name' => 'surname',
            'type' => 'text',
            'validation' => 'required',
        ],
        [
            'caption' => 'Email',
            'name' => 'email',
            'type' => 'email',
            'validation' => 'required|email',
        ],
        [
            'caption' => 'Birth date',
            'name' => 'birthDate',
            'type' => 'date',
            'validation' => 'required|date_format:Y-m-d',
        ],
        [
            'caption' => 'Photo',
            'name' => 'photo',
            'type' => 'file',
            'validation' => 'image|max:1024',
        ],
    ];

    public bool $showStatus = false;

    public ?string $username = null;
    public ?string $name = null;
    public ?string $surname = null;
    public ?string $email = null;
    public ?string $birthDate = null;
    public TemporaryUploadedFile|string|null $photo = null;

    public function toggleShowStatus(): void
    {
        $this->showStatus = !$this->showStatus;
    }

    public function updated(string $propertyName): void
    {
//        Preview:
//        'username', ['username' => 'required|min:6|unique:employees,username']
        $this->validateOnly(
            $propertyName,
            collect(self::EMPLOYEE_PROPERTIES)->where('name', $propertyName)
                ->pluck('validation', 'name')
                ->toArray()
        );
    }

    public function submit(): void
    {
//        Preview:
//        [
//            'username' => 'required|min:6|unique:employees,username',
//            'name' => 'required',
//            'surname' => 'required',
//            ...
//        ]
        $this->validate(
            collect(self::EMPLOYEE_PROPERTIES)->pluck('validation', 'name')
                ->toArray()
        );

        $photoPath = $this->photo->store('photos', ['disk' => 'public']);
        Employee::create(array_merge(
            $this->only(
                collect(self::EMPLOYEE_PROPERTIES)->pluck('name')
                    ->toArray()
            ),
            ['photo' => $photoPath],
        ));

        $this->reset();
        $this->emit('refreshEmployeeList');
        session()->flash('message', 'Employee has been added.');
    }

    public function render(): View
    {
        return view('livewire.add-employee', [
            'employeeProperties' => self::EMPLOYEE_PROPERTIES,
        ]);
    }
}

app/Http/Livewire/DeleteEmployee.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use App\Models\Employee;
use Illuminate\View\View;
use Livewire\Component;

class DeleteEmployee extends Component
{
    public bool $showStatus = false;

    public ?Employee $employee = null;

    protected $listeners = [
        'selectEmployeeToDelete' => 'selectEmployeeToDelete',
    ];

    public function deleteEmployee(): void
    {
        $this->showStatus = false;
        $this->employee->delete();

        $this->emit('refreshEmployeeList');
        $this->emitTo(
            'main-message',
            'showMessage',
            'success',
            sprintf('Employee "%s" has been deleted', $this->employee->username)
        );
    }

    public function selectEmployeeToDelete(Employee $employee): void
    {
        $this->employee = $employee;
        $this->showStatus = true;
    }

    public function render(): View
    {
        return $this->showStatus === false ?
            view('livewire.void-holder') :
            view('livewire.delete-employee');
    }
}

app/Http/Livewire/EmployeeCalendar.php
<?php

namespace App\Http\Livewire;

use App\Models\Employee;
use Asantibanez\LivewireCalendar\LivewireCalendar;
use Carbon\Carbon;
use Illuminate\Support\Collection;

class EmployeeCalendar extends LivewireCalendar
{
    public function events(): Collection
    {
        return Employee::all()->map(function($employee): array {
            return [
                'id' => $employee->id,
                'title' => $employee->username,
                'description' => $employee->name,
                'date' => $employee->birthDate,
            ];
        });
    }

    public function onEventDropped($eventId, $year, $month, $day)
    {
        Employee::find($eventId)->update([
            'birthDate' => Carbon::parse("{$year}-{$month}-{$day}")
        ]);
    }
}

app/Http/Livewire/EmployeeChangeNotifier.php
<?php

namespace App\Http\Livewire;

use App\Models\Employee;
use Livewire\Component;

class EmployeeChangeNotifier extends Component
{
    public int $count;

    public function checkActualEmployeeCount(): void
    {
        $newCount = $this->getCount();
        if ($newCount !== $this->count) {
            $this->emitTo(
                'main-message',
                'showMessage',
                'error',
                'Something has changed on the list'
            );
        }
        if ($newCount === 0) {
            redirect()->to('/empty-list');
        }
        $this->count = $newCount;
    }

    public function mount(): void
    {
        $this->count = $this->getCount();
    }

    private function getCount(): int
    {
        return Employee::count();
    }

    public function render()
    {
        return view('livewire.employee-change-notifier');
    }
}

app/Http/Livewire/MainMessage.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use Illuminate\View\View;
use Livewire\Component;

class MainMessage extends Component
{
    public ?string $type = null;

    public ?string $message = null;

    protected $listeners = [
        'showMessage' => 'handleMessage',
    ];

    public function hideMessageBox(): void
    {
        $this->message = null;
    }

    public function handleMessage(string $type, string $message): void
    {
        $this->type = $type;
        $this->message = $message;
    }

    public function render(): View
    {
        return is_null($this->message) ?
            view('livewire.void-holder') :
            view('livewire.main-message');
    }
}

app/Http/Livewire/PreviewEmployee.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use App\Models\Employee;
use Livewire\Component;

class PreviewEmployee extends Component
{
    public bool $showStatus = false;

    public ?Employee $employee = null;

    public ?int $employeeId = null;

    protected $queryString = ['employeeId'];

    protected $listeners = [
        'openModal' => 'selectEmployeeToPreview',
    ];

    public function mount(): void
    {
        if (is_null($this->employeeId)) {
            return;
        }
        $this->selectEmployeeToPreview(
            Employee::find($this->employeeId)
        );
    }

    public function selectEmployeeToPreview(Employee $employee): void
    {
        $this->employee = $employee;
        $this->employeeId = $this->employee->id;
        $this->showStatus = true;
    }

    public function render()
    {
        return $this->showStatus === false ?
            view('livewire.void-holder') :
            view('livewire.preview-employee');
    }
}

app/Http/Livewire/SearchEmployee.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use Illuminate\View\View;
use Livewire\Component;
use Psr\Log\LoggerInterface;

class SearchEmployee extends Component
{
    public const RESULT_LIST_ELEMENT_ID = 'search';

    public ?string $searchQuery = null;

    private LoggerInterface $logger;

    public function boot(LoggerInterface $logger): void
    {
        $this->logger = $logger;
    }

    public function updatedSearchQuery(string $searchQuery): void
    {
        $this->logger->info($this->searchQuery);
        $this->emitTo(
            'show-employee-list',
            'setSearchQuery',
            self::RESULT_LIST_ELEMENT_ID,
            $searchQuery
        );
    }

    public function render(): View
    {
        return view('livewire.search-employee');
    }
}

app/Http/Livewire/SearchField.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use Illuminate\View\View;
use Livewire\Component;

class SearchField extends Component
{
    public ?string $query = null;

    public function render(): View
    {
        return view('livewire.search-field');
    }
}

app/Http/Livewire/ShowEmployeeCard.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use App\Models\Employee;
use Illuminate\View\View;
use Livewire\Component;

class ShowEmployeeCard extends Component
{
    public Employee $employee;

    public function render(): View
    {
        return view('livewire.show-employee-card');
    }
}

app/Http/Livewire/ShowEmployeeList.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use App\Models\Employee;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\View\View;
use Livewire\Component;
use Livewire\WithPagination;

class ShowEmployeeList extends Component
{
    use WithPagination;

    public ?string $searchQuery = null;

    public ?string $elementId = null;

    public int $limit = 5;

    public string $viewType = 'list';

    protected $queryString = [
        'page' => ['except' => 1],
        'limit',
        'viewType',
    ];

    protected function getListeners(): array
    {
        return [
            'refreshEmployeeList' => '$refresh',
            'setSearchQuery' => 'setSearchQuery',
        ];
    }

    public function setSearchQuery(string $elementId, string $searchQuery): void
    {
        if ($elementId !== $this->elementId) {
            return;
        }
        $this->searchQuery = $searchQuery;
    }

    public function updatedLimit()
    {
        $this->resetPage();
    }

    private function getEmployeeResults(): LengthAwarePaginator
    {
        return Employee::where(function($query) {
            if (!is_null($this->searchQuery)) {
                $query->where('username', 'like', "%{$this->searchQuery}%");
            }
        })->orderBy('id', 'desc')
            ->paginate($this->limit);
    }

    public function render(): View
    {
        return view(
            $this->viewType === 'list' ?
                'livewire.show-employee-list' :
                'livewire.show-employee-cards',
            [
                'employees' => $this->getEmployeeResults(),
            ]
        );
    }
}

app/Http/Livewire/ShowEmployeeRow.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use App\Models\Employee;
use Faker\Generator;
use Illuminate\Support\Facades\App;
use Illuminate\View\View;
use Livewire\Component;

class ShowEmployeeRow extends Component
{
    public Employee $employee;

    public function setRandomEmail(): void
    {
        $this->employee->email = App::make(Generator::class)->safeEmail();
        $this->employee->save();
        $this->emit('refreshEmployeeList');
    }

    public function render(): View
    {
        return view('livewire.show-employee-row');
    }
}

resources/views/livewire/add-employee.blade.php
<div>
    <div class="max-w-sm smx-auto bg-white shadow py-5 px-6 mt-16">
        <h2 class="text-xl">Add new employee</h2>

    @if (session()->has('message'))
        <div class="text-green-500">
            {{ session('message') }}
        </div>
    @endif

    <button wire:click="toggleShowStatus" class="mt-6 bg-sky-500 hover:bg-sky-700 px-5 py-2.5 text-sm leading-5 rounded-md font-semibold text-white">{{ $showStatus === true ? 'Hide' : 'Show' }} form</button>

    @if ($showStatus)
        <form wire:submit.prevent="submit" class="animation-linear animation-duration-500 {{-- $showStatus === false ? 'animate-hide' : 'animate-show' --}}">

            @foreach ($employeeProperties as $field)
            <div class="mt-6">
                <label for="{{ $field['name'] }}" class="block text-sm font-medium text-slate-700">{{ $field['caption'] }}</label>
                <div class="mt-1">
                    <input type="{{ $field['type'] }}" name="{{ $field['name'] }}" id="{{ $field['name'] }}" wire:model.lazy="{{ $field['name'] }}" class="px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-sm focus:ring-1 invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500 disabled:shadow-none" value="">
                </div>

                @if ($field['type'] === 'file' && ${$field['name']} !== null)
                    Preview:
                    <img src="{{ ${$field['name']}->temporaryUrl() }}">
                @endif

                @if ($errors->has($field['name']))
                    <span class="text-pink-500">{{ $errors->first($field['name']) }}</span>
                @endif
            </div>
            @endforeach

            <div class="mt-6 text-right">
                <button class="bg-sky-500 hover:bg-sky-700 px-5 py-2.5 text-sm leading-5 rounded-md font-semibold text-white">Save</button>
            </div>
        </form>
    @endif

    </div>
</div>

resources/views/livewire/delete-employee.blade.php
@extends('livewire.parts.modal-layout')

@section('title', 'Delete employee record #'.$employee->id)

@section('description')
    Deleting {{ $employee->username }} Are you sure?
@endsection

@section('action-buttons')
    <button type="button" wire:click="deleteEmployee" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm">Delete</button>
    <button type="button" wire:click="$set('showStatus', false)" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">Cancel</button>
@endsection

resources/views/livewire/employee-change-notifier.blade.php
<div wire:poll.10s.keep-alive="checkActualEmployeeCount" class="max-w-sm smx-auto bg-white shadow py-5 px-6 mt-16">
    <h2 class="text-xl">Notifier</h2>

    {{ $count }}
</div>

resources/views/livewire/main-message.blade.php
<div>
    <div wire:poll.6s="hideMessageBox" class="w-full justify-center rounded-md border border-transparent shadow-sm px-4 py-2 mt-2 mb-6 {{ $type === 'success' ? 'bg-green-300' : 'bg-red-300' }} text-xl text-white sm:w-auto">{{ $message }}</div>
</div>

resources/views/livewire/preview-employee.blade.php
@extends('livewire.parts.modal-layout')

@section('title')
    Employee <b>{{ $employee->username }}</b> preview
@endsection

@section('description')
    <img src="{{ $employee->photo_link }}" />

    @foreach ($employee->toArray() as $key => $val)
        <div>{{ $key }}: {{ $val }}</div>
    @endforeach
@endsection

@section('action-buttons')
    <button type="button" wire:click="$set('showStatus', false)" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">Close</button>
@endsection

resources/views/livewire/search-employee.blade.php
<div>
    <input type="text" wire:model.debounce.500ms="searchQuery" class="w-full p-2 rounded" placeholder="Search for...">

    <div class="h-6">{{ !empty($searchQuery) ? sprintf('Searching for: "%s"', $searchQuery) : '' }}</div>
    <div class="h-6"><span class="hidden" wire:loading.inline>Loading</span></div>

    @if (!empty($searchQuery))
        <livewire:show-employee-list viewType="cards" :element-id="App\Http\Livewire\SearchEmployee::RESULT_LIST_ELEMENT_ID" />
    @endif
</div>

resources/views/livewire/search-field.blade.php
<div>
    <input type="text" wire:model="query" class="py-4">

    <div wire:loading.class.200s="border-2">Loading</div>
    <div>Searching for: {{ $query }}</div>
</div>

resources/views/livewire/show-employee-card.blade.php
<div wire:click="$emitTo('preview-employee', 'openModal', {{ $employee }})" class="border-solid border-2 border-black-600 bg-white rounded m-1 p-2 w-1/4">
    <h3>#{{ $employee->id }} {{ $employee->username }}</h3>
    @if (!is_null($employee->photo))
        <img src="{{ $employee->photo_link }}">
    @endif
    <div class="text-xs">{{ $employee->name }} {{ $employee->surname }}</div>
</div>

resources/views/livewire/show-employee-cards.blade.php
<div>
    @include('livewire.parts.switch-view-type')

    <select wire:model="limit">
        <option>5</option>
        <option>10</option>
    </select>

    <div class="w-full flex flex-wrap">
    @foreach ($employees as $employee)
        <livewire:show-employee-card :employee="$employee" :wire:key="'employee-card-'.$employee->id.'-'.$employee->updated_at->timestamp" />
    @endforeach
    </div>

    {{ $employees->links() }}
</div>

resources/views/livewire/show-employee-list.blade.php
<div>
    @include('livewire.parts.switch-view-type')

    <select wire:model="limit">
        <option>5</option>
        <option>10</option>
    </select>

    <div class="table w-full bg-white shadow rounded">
        <div class="table-header-group">
            <div class="table-row">
                <div class="table-cell p-2"></div>
                <div class="table-cell p-2">Id</div>
                <div class="table-cell p-2">Username</div>
                <div class="table-cell p-2">Name</div>
                <div class="table-cell p-2">Surname</div>
                <div class="table-cell p-2">Email</div>
                <div class="table-cell p-2">Birth date</div>
                <div class="table-cell p-2">Action</div>
            </div>
        </div>

        <div class="table-row-group">
        @foreach ($employees as $employee)
            <livewire:show-employee-row :employee="$employee" :wire:key="'employee-row-'.$employee->id.'-'.$employee->updated_at->timestamp" />
        @endforeach
        </div>
    </div>

    {{ $employees->links() }}
</div>

resources/views/livewire/show-employee-row.blade.php
<div class="table-row">
    <div class="table-cell p-2">
        <input type="checkbox">
    </div>
    <div class="table-cell p-2">{{ $employee->id }}</div>
    <div class="table-cell p-2">{{ $employee->username }}</div>
    <div class="table-cell p-2">{{ $employee->name }}</div>
    <div class="table-cell p-2">{{ $employee->surname }}</div>
    <div class="table-cell p-2">
        {{ $employee->email }}
        <button wire:click="setRandomEmail" class="bg-red-500 hover:bg-red-700 px-3 py-1 text-sm leading-5 rounded-md font-semibold text-white">Random</button>
    </div>
    <div class="table-cell p-2">{{ $employee->birthDate->format('Y-m-d') }}</div>
    <div class="table-cell p-2">
        <button wire:click="$emitTo('delete-employee', 'selectEmployeeToDelete', {{ $employee->id }})" class="bg-red-500 hover:bg-red-700 px-3 py-1 text-sm leading-5 rounded-md font-semibold text-white">Delete</button>
    </div>
</div>

resources/views/livewire/void-holder.blade.php
<div>

</div>